spring.application.name=marketplace
spring.data.mongodb.uri=mongodb+srv://Akmuchhala:Akmuchhala3009@cluster0.fps9an5.mongodb.net/marketplace?retryWrites=true&w=majority
server.port=8080
# Enable static content mapping
spring.web.resources.static-locations=classpath:/static/
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=1000MB
